language: php

branches:
  only:
    - master
    - develop

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - composer self-update
  - composer --version
  - composer install --no-interaction

script:
  - mkdir build
  - ./vendor/bin/phpunit -c test/phpunit.xml --coverage-clover build/clover.xml
  - ./vendor/bin/phpcs --standard=PSR2 --ignore=./test/bootstrap.php ./src/ ./test/

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover build/clover.xml